variable "app_service_plan_name" {}
variable "location" {}
variable "resource_group_name" {}
variable "backend_app_name" {}
variable "frontend_app_name" {}
variable "database_url" {}
variable "db_server_name" {}
variable "db_admin_user" {}
variable "db_admin_password" {}
variable "db_name" {}
variable "tags" {}