variable "db_server_name" {}
variable "location" {}
variable "resource_group_name" {}
variable "sku_name" {}
variable "admin_username" {}
variable "admin_password" {}
variable "storage_endpoint" {}
variable "db_name" {}
variable "subnet_id" {}