variable "db_server_name" {}
variable "location" {}
variable "resource_group_name" {}
variable "sku_name" {}
variable "admin_username" {}
variable "admin_password" {}
variable "db_name" {}
variable "subnet_id" {}
variable "app_subnet_id" {}
variable "vnet_id" {}
variable "tags" {}
variable "vm_admin_password" {}